#!/bin/sh
# xinitrc

# Run all system xinitrc scripts in /etc/X11/xinit/xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		. "$f"
	done
	unset f
fi

# Ensure dbus is running and DBUS_SESSION_BUS_ADDRESS is set
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && eval "$(dbus-launch --sh-syntax --exit-with-x11)"

# X11 configuration
[ -f "$XMODMAP" ] && xmodmap "$XMODMAP"
[ -f "$XRESOURCES" ] && xrdb -merge "$XRESOURCES"
xset r rate 300 45
xset s off
xset dpms 0 0 0
xset -dpms

# Start DE/WM
export DESKTOP_SESSION=plasma
exec startplasma-x11
