#!/bin/sh
# xinitrc

# Run all system xinitrc scripts in /etc/X11/xinit/xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		. "$f"
	done
	unset f
fi

# X11 configuration
[ -f "$XMODMAP" ] && xmodmap "$XMODMAP"
[ -f "$XRESOURCES" ] && xrdb -merge "$XRESOURCES"
xset r rate 300 45

# Start DE/WM
exec qtile start
