# starship config (starship.toml)

add_newline = false

continuation_prompt = ' '

format="""\
$username\
$character\
$cmd_duration\
$git_branch\
$directory\
"""

[username]
style_root = 'fg:bright-white bg:black'
style_user = 'fg:bright-white bg:black'
format = '[](black)[$user]($style)[](black) '
show_always = false
disabled = false

[character]
error_symbol = '[](red)[!](fg:black bg:red bold)[](red) '
success_symbol = ''
vimcmd_replace_one_symbol = ''
vimcmd_replace_symbol = ''
vimcmd_symbol = ''
vimcmd_visual_symbol = ''
format = '$symbol'
disabled = false

[cmd_duration]
style  = 'fg:black bg:yellow bold'
format = '[](yellow)[$duration]($style)[](yellow) '
min_time = 5000
min_time_to_notify = 60000
show_milliseconds = false
show_notifications = false
disabled = false

[git_branch]
style = 'fg:black bg:purple'
symbol = ''
format = '[](purple)[$symbol $branch(:$remote_branch)]($style)[](purple) '
always_show_remote = false
only_attached = false
truncation_symbol = '…'
disabled = false

[directory]
style = 'fg:black bg:bright-white'
format = '[](bright-white)[$path]($style)[](bright-white) '
home_symbol = '~'
truncate_to_repo = true
truncation_length = 4
truncation_symbol = '…/'
disabled = false
