# 'Iceberg Dark' colorscheme for alacritty (colorschemes/IcebergDark.toml)
[colors.normal]
black = '#1e2132'
red = '#e27878'
green = '#b4be82'
yellow = '#e2a478'
blue = '#84a0c6'
magenta = '#a093c7'
cyan = '#89b8c2'
white = '#c6c8d1'

[colors.bright]
black = '#6b7089'
red = '#e98989'
green = '#c0ca8e'
yellow = '#e9b189'
blue = '#91acd1'
magenta = '#ada0d3'
cyan = '#95c4ce'
white = '#d2d4de'

[colors.dim]
black = '#1e2132'
red = '#e27878'
green = '#b4be82'
yellow = '#e2a478'
blue = '#84a0c6'
magenta = '#a093c7'
cyan = '#89b8c2'
white = '#c6c8d1'

[colors.primary]
background = '#161821'
foreground = '#c6c8d1'
bright_foreground = 'None'
dim_foreground = '#c6c8d1'

[colors.cursor]
cursor = '#c6c8d1'
text = '#161821'

[colors.footer_bar]
background = '#161821'
foreground = '#c6c8d1'

[colors.hints]
start = { background = '#84a0c6', foreground = '#161821' }
end = { background = '#84a0c6', foreground = '#161821' }

[colors.line_indicator]
background = '#161821'
foreground = '#c6c8d1'

[colors.search]
matches = { background = '#e4aa80', foreground = '#392313' }
focused_match = { background = 'CellForeground', foreground = 'CellBackground' }

[colors.selection]
background = '#272c42'
text = 'CellForeground'

[colors.vi_mode_cursor]
cursor = '#c6c8d1'
text = '#161821'
